# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-02-26 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronograph', '0003_auto_20200226_1007'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['run_date'], name='run_date_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['job', 'run_date'], name='run_date_by_job_idx'),
        ),
    ]
